### ISSUE TITLE
Example files for reproducing the R code. 

### ISSUE THREAD

**Issue by xie186** [myonaung/Pf3K_Scripts#1]
Hi @myonaung,

Thank you for sharing the code. 

In the two lines below, we do not see the corresponding files provided in the github link: 

https://github.com/myonaung/Naung-et-al-2021/blob/89143c5d5f92cf919689e99b564adbc2292af436/Phasing_Haplotype/pf3k_antigen.Rmd#L68

https://github.com/myonaung/Naung-et-al-2021/blob/89143c5d5f92cf919689e99b564adbc2292af436/Phasing_Haplotype/pf3k_antigen.Rmd#L349

Could you please let us know what columns are included in `pf3kv5_functional_annotations_filtered.rds` and what are the `*.1.fasta` files? Thanks again!

**Comment by myonaung** [comment]
@xie186 , Thanks very much for your interest in our published manuscript. Please see example .rds file at 
[pf3kv5_functional_annotations_filtered_subset.csv](https://github.com/myonaung/Naung-et-al-2021/files/8876023/pf3kv5_functional_annotations_filtered_subset.csv).

`*.1.fasta ` can be any reference file excluding intronic region. 

Let me know if you have any further questions

**Comment by xie186** [comment]
Thank you so much for you help @myonaung !
