### ISSUE TITLE
Questions on Fig. 1 

### ISSUE THREAD

**Issue by xie186** [myonaung/Pf3K_Scripts#2]
Hi @myonaung , Regarding the ridgeline plot in Fig. 1, my understanding is that you used the Tajima's D values for each of the windows for each of the antigens. Am I correct?

**Comment by myonaung** [comment]
Tajima's D value (single value without sliding window). The distribution is from different countries where i treated different country as different populations.

**Comment by xie186** [comment]
Thank you @myonaung!
